### ISSUE TITLE
Planning for March 2015

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#22]
March 23.

**Comment by matthias-stone** [comment]
Bill Kennedy has volunteered to do a mongodb talk.

Brett has an interesting idea that we could follow up on as an alternative to talks.

**Comment by nathany** [comment]
:+1: Interesting ideas.

**Comment by nathany** [comment]
Would Brett's idea be doable in 15-20 minutes?

**Comment by nathany** [comment]
Unfortunately Bill Kennedy isn't going to be able to make it on Monday. For a backup plan, we can probably pick any one of the GopherCon India talks to show.

**Comment by nathany** [comment]
Bill is going to try to make it for April's meetup instead.

There are several videos from GopherCon India.
https://www.youtube.com/channel/UCa-OZB5VIMcdzgrXRM2U0Ww

There was also FOSDEM and others recently. See:
http://gophervids.appspot.com/

**Comment by matthias-stone** [comment]
Ones that stand out to me (By Title):
GopherCon India:
* Optimizing Go Programs
* Embracing the Standard Library
* Concurrency By Data Structures
* Web Development using Go And Ember
FOSDEM
* HTTP/2 for Go
* State of Go
* Go at CoreOS
* Go and the modern Enterprise

I think I'll watch these, and give people a choice of the best two or three.

Brett's idea was, rather than a straight up talk, have someone lead a discussion and draw answers from the audience. He thinks it would be more interactive and require less work. An example topic would be: How do I interact with a RESTful web service in Go? Then you would just have a simple example (interact with Github), and explore handling setting authentication http header, parsing data, etc.
If I can come up with a good idea by tomorrow I wold like to try this.

**Comment by nathany** [comment]
I've watched the FOSDEM ones, pretty good. Here are a few more suggestions:

This designing APIs with channels sounds good
https://www.youtube.com/watch?v=hFqXgmor74k

I really like this Channeling Failure talk so far
http://youtu.be/lzlGXMnrBgw

An interactive discussion would be great. Would be nice to mix it up a bit.
