### ISSUE TITLE
November 2017

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#71]
~~October 23rd~~
November 27th

Concurrency talk?

**Comment by grrtrr** [comment]
Do you have anything specific in mind for concurrency? It is something I am interested in, too.

**Comment by nathany** [comment]
People were asking for talks on concurrency at the last meetup. That could span quite a few topics/talks.

**Comment by grrtrr** [comment]
Would be happy to prepare something, now that the date has moved (October is still busy). Is there any particular topic or focus (introductory, packages, patterns, caveats) or preference you'd like me to prepare for?

**Comment by nathany** [comment]
We have one talk:
"concurrency in go: an introduction to channels" - Tobias Renwick

@grrtrr Any ideas for something that would complement that talk? Or perhaps something entirely different that you've played around with lately?

**Comment by grrtrr** [comment]
@nathany - I am not sure that I can add useful [`context`](https://github.com/golang/go/issues/20280) to this. 

Some projects and frameworks now exist [[1](https://github.com/dc0d/actorloop), [2](https://github.com/AsynkronIT/protoactor-go), [3](https://github.com/teivah/gosiris)], but I have not looked in depth at any.

Over the months observed that the [Actor Model](https://www.quora.com/What-is-an-example-in-nature-of-concurrency-or-the-actor-model)  proves really very useful for concurrent programming.

Hence my _suggestion_: Peter Bourgon gave a [nice talk](https://www.youtube.com/watch?v=LHe1Cb_Ud_M) on concurrent programming. Since he worked at the same place as [Bryan Boreham](https://www.slideshare.net/weaveworks/an-actor-model-in-go-65174438), there is some mention, along with best practices.
