### ISSUE TITLE
January 2019

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#95]
January 28, 2019 meetup. We have some time to plan for this one!

**Comment by stellentus** [comment]
@nathany I'd find that very interesting, but I won't be able to attend. If your slides are readable on their own, I'll read them.

Or maybe you'll record the talk? Mathias and I have talked about doing that at some point for his talks. Maybe you could be the trial run. It would be nice if Edmonton Go could share some of our local talks with others, since we benefit from other recorded talks. But it might be too much work to set up.

**Comment by nathany** [comment]
@stellentus Thanks James. I'm asking @MarkBennett about the gear and someone to help to record the Go meetup, Or I may give the talk again at the JS meetup if there is interest -- in which case it should be recorded.

**Comment by nathany** [comment]
@stellentus I'll be giving the same talk again on February 7th for the Exchange.js meetup, though tailored more for people who know JavaScript but not Go. It should be recorded and available on YouTube.

**Comment by nathany** [comment]
@stellentus The recording is available at: https://youtu.be/N8Fc7RQfmdU
